ALTER TABLE "Product"
ALTER COLUMN "inStock" DROP DEFAULT;

ALTER TABLE "Product"
ALTER COLUMN "inStock" TYPE INTEGER
USING CASE
  WHEN "inStock" = TRUE THEN 10
  ELSE 0
END;

ALTER TABLE "Product"
ALTER COLUMN "inStock" SET DEFAULT 0;
